### ISSUE TITLE
H5P crossword Type

### ISSUE THREAD

**Issue by englishwebtls** [dthies/moodle-contenttype_repurpose#4]
Hello 
Could you please add the H5P crossword type to the list?
I would very much appreciate it.
Thanks very much.

**Comment by dthies** [comment]
I have a development version on my demo site https://moodle.openlearner.org. You can create a free account there, and import questions to create crosswords. There are other content types available there as well. Any feedback you can give will be helpful. I only want to release when I know something is stable. The crossword content type was listed as beta on h5p.org until recently.

**Comment by englishwebtls** [comment]
Hello Daniel
Thank you for your email. As far as I can tell the H5P crossword is out of
Beta. How can I find out for certain?

Thank you very much for all your work on your excellent H5P plugins. Much
appreciated!

Regards,
Nyree

**Comment by dthies** [comment]
I released this now. Please let me know if you have any issues with it.

**Comment by englishwebtls** [comment]
THANK YOU !
